name: CLI CI

on:
  pull_request:
    paths:
      - 'cli/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.13.8'

      - name: Build
        run: make
        working-directory: cli

      - name: Test
        run: make test
        working-directory: cli
