name: CLI CI (Rust)

on:
  pull_request:
    paths:
      - 'cli-rust/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Check code style
        run: cargo fmt -- --check
        working-directory: cli-rust

      - name: Build
        run: cargo build
        working-directory: cli-rust

      - name: Test
        run: cargo test
        working-directory: cli-rust
